<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_user</name>
   <tag></tag>
   <elementGuidId>3d4a3791-5ee5-4fe8-9991-1f1373b24977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_user']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'email_user' and @id = 'email_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fcdf49f-87dc-4336-a2ad-cc37b279f871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-bottom-border</value>
      <webElementGuid>69fe5058-f22b-40a7-88d0-4962dd12c5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>945c255e-7e34-4c90-a5fe-2bba7f1cd5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_user</value>
      <webElementGuid>1cdcca8a-27e8-443b-98f2-c7a2fa39731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_user</value>
      <webElementGuid>c9376191-af45-4615-84f6-c9a1465da492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_user&quot;)</value>
      <webElementGuid>473b4504-6482-44f7-aaad-811a2f57c2fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_user']</value>
      <webElementGuid>1a6d8aeb-b72f-480e-8b5a-d40f6b033fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]/input</value>
      <webElementGuid>c0ff75b3-a62c-40c6-9804-44742a823c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2f855d56-fcef-4713-928e-051f6d115c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_user' and @id = 'email_user']</value>
      <webElementGuid>4020a99d-3ab8-4c99-ae9c-2a2b61316bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
