<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Session</name>
   <tag></tag>
   <elementGuidId>21381c77-80e9-4ce5-899e-3c0102e5395c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.profile-v4-btn-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d0accb6-3185-4ac5-b888-e9b1d5f0361e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91026dbb-2999-458c-981b-dcd6e8b7c1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-v4-btn-info</value>
      <webElementGuid>abc6e1f3-310c-4f82-b3b4-74065111311d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>get_session()</value>
      <webElementGuid>6ec5fbed-d039-452c-83bb-250e92be951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Session</value>
      <webElementGuid>70c0b895-7155-46e0-b5b6-4288350ebf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper-40&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container-dl&quot;]/div[@class=&quot;profile-v4-grid-2&quot;]/div[@class=&quot;profile-v4-card&quot;]/div[@class=&quot;profile-v4-db-controls&quot;]/button[@class=&quot;profile-v4-btn-info&quot;]</value>
      <webElementGuid>f933d627-7ff5-47ff-8a19-2a271623b0e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>bbe88547-bf33-45cf-a4c3-25e1a4fdfc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper-40']/div[3]/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>44789471-01ce-4c7d-9ddb-8b9c99549fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Token'])[1]/following::button[1]</value>
      <webElementGuid>53199c5d-b032-4d76-a702-575a77229c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session Inactive'])[1]/following::button[2]</value>
      <webElementGuid>b72357a1-659d-4773-9a72-da4d37389b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Session']/parent::*</value>
      <webElementGuid>694557da-383b-42bc-8011-315fd778139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/button</value>
      <webElementGuid>f924da0f-5015-4b0d-a625-67f8e40e9008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Get Session' or . = 'Get Session')]</value>
      <webElementGuid>f2b2dd26-a93f-4c27-9d36-7be5f4aa08c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
