<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Customer</name>
   <tag></tag>
   <elementGuidId>a37f9b5b-57df-4b7d-874c-e3de3bdbc5a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subpanelItems40']/a[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69344768-f031-441a-b8eb-4f62aa122517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dummy.appoaktree.id/admin/master_customer</value>
      <webElementGuid>c16dcee8-95c8-4cb2-bda2-1c2e823c73d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>fcbf7de6-1e36-48dd-8c1e-b0531feb5bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpanelItems40&quot;)/a[6]</value>
      <webElementGuid>a5601c72-60d1-4c26-8ecf-c592f5e8c45a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subpanelItems40']/a[6]</value>
      <webElementGuid>60bced62-aa8c-4a06-9b2c-4cbc5cdcad98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::a[1]</value>
      <webElementGuid>af2e0b37-7cc9-4113-a783-fccfed424f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/following::a[2]</value>
      <webElementGuid>99c60f52-35d3-4f8f-be83-24873c4b8565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depo'])[1]/preceding::a[1]</value>
      <webElementGuid>c79b0d47-ed50-4e4e-aead-5f0b51836bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dummy.appoaktree.id/admin/master_customer')]</value>
      <webElementGuid>19ed09ce-6281-4ddf-bf96-3e83549448e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>935b5bf9-afa9-4c31-8deb-ebd2a6d865fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dummy.appoaktree.id/admin/master_customer' and (text() = 'Customer' or . = 'Customer')]</value>
      <webElementGuid>dfd87492-c55f-46f9-a871-90ecd7888ce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
