<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-profile</name>
   <tag></tag>
   <elementGuidId>31aec009-4846-4ab8-954a-d17a8c316b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sidebarnav']/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sidebar-40-bottom-item.sidebar-40-profile > img.profile-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71de0f08-0cb2-4687-9989-8e439e93193a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-avatar</value>
      <webElementGuid>979655fa-169b-4a83-b897-c12a637113ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=Zharfan</value>
      <webElementGuid>93ce33b8-d91e-43e1-8434-a126e4a87364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Zharfan</value>
      <webElementGuid>3685ee68-f522-409d-bd47-192d8a1dc073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarnav&quot;)/li[@class=&quot;sidebar-40-bottom&quot;]/a[@class=&quot;sidebar-40-bottom-item sidebar-40-profile&quot;]/img[@class=&quot;profile-avatar&quot;]</value>
      <webElementGuid>db39bc62-f34b-4659-9b2d-16a2327d2b9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarnav']/li/a/img</value>
      <webElementGuid>0567b4cb-c45e-4165-b0d0-4b9255ff3334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Zharfan']</value>
      <webElementGuid>4ce569a2-a4ac-410f-a90f-43f61e12b882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>2f61eafc-4f5f-4ec4-ad6d-15bf0a06ada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=Zharfan' and @alt = 'Zharfan']</value>
      <webElementGuid>578b0d73-1e44-41d9-926e-d72180aa4b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
