<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Jobfile</name>
   <tag></tag>
   <elementGuidId>a52c0548-6eec-4c55-9c9d-449b62a57388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subpanelItems40']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subpanelItems40 > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f7ebb2b-ace4-4a0d-8bcf-bb7a9018b466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dummy.appoaktree.id/admin/jobfile</value>
      <webElementGuid>8fbeeaf5-6e58-4473-a57b-dafebb36236a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jobfile</value>
      <webElementGuid>caae377f-5cc0-47f1-9acd-9ee325f8de56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpanelItems40&quot;)/a[2]</value>
      <webElementGuid>317d5890-8f05-4cb1-8133-7ba7f8a3fd69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subpanelItems40']/a[2]</value>
      <webElementGuid>92f1e6b8-0512-48db-9e8e-937799a54ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>73d2789e-7a6b-487e-9f01-854cf9c353f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational'])[2]/following::a[2]</value>
      <webElementGuid>efcca330-210d-48cf-901c-bb22b931ef70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Copy'])[1]/preceding::a[1]</value>
      <webElementGuid>1b7312d8-202e-41fa-8ec2-d5537094cbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dummy.appoaktree.id/admin/jobfile')]</value>
      <webElementGuid>66e533c6-7f25-4378-994d-34346d583c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>ec562c5e-0730-42e0-99bd-112c1191ec74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dummy.appoaktree.id/admin/jobfile' and (text() = 'Jobfile' or . = 'Jobfile')]</value>
      <webElementGuid>ff068709-c17e-4cd0-9f76-8fe52c0ea89f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
