<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tax Payer Name_tax_name</name>
   <tag></tag>
   <elementGuidId>d0950a48-5495-4aa6-b8a5-9ad420bc6ba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tax_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tax_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ad679df-f7c7-44d0-b274-908ad54f742c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1c0f319-213a-4b68-82e9-3b138b800153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>4d2e51be-f00d-4d34-adaf-7788fbbfddfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tax_name</value>
      <webElementGuid>ac38469c-b43d-40f5-8413-37cf84398749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_name</value>
      <webElementGuid>c22852fa-7f13-452d-87d7-4fa32bc2692b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tax Name</value>
      <webElementGuid>47d8d4bb-d2ba-46c8-abd0-1d4b9ac612d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax_name&quot;)</value>
      <webElementGuid>3c51c95f-c839-4b01-8223-ca3953d9ceae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tax_name']</value>
      <webElementGuid>199dec44-9af8-4807-8e27-7c9a2a6bc124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form-p-4']/div/div[2]/div/div/input</value>
      <webElementGuid>a4a62c97-e107-4ebd-a9c4-ecae251a99eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div[2]/div/div/input</value>
      <webElementGuid>65c24937-fefc-4dc8-82bf-aa5d265472da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tax_name' and @name = 'tax_name' and @placeholder = 'Tax Name']</value>
      <webElementGuid>b6c47dc3-1544-42b3-826f-2918beba749c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
