<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Position_pic_position</name>
   <tag></tag>
   <elementGuidId>b8a78044-18cb-4276-9937-12bcc20c81f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pic_position[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pic_position[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88881c8e-cda7-4f40-aa6c-fed3fb145155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6aa8fbe5-30fe-4354-812c-5d587cbab1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pic_position[]</value>
      <webElementGuid>2df3f331-b6a1-4c9f-95c5-36200ced9896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>9eb0457a-f0f8-445a-84f4-3d64b6f60877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pic_field&quot;)/div[@class=&quot;form-group m-b-0 pic-field0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 nopadding&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>bf542f35-337e-4fdb-b682-a7286279f025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pic_position[]']</value>
      <webElementGuid>2503661c-d995-46fd-aef8-16b2930d6328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pic_field']/div/div/div[4]/div/input</value>
      <webElementGuid>80565422-642d-43ea-a808-b8ba3df0052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>123e776c-602c-4117-b1b3-e5dec4edb5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pic_position[]']</value>
      <webElementGuid>6e8f78cd-dc44-451a-b522-51f7e5d072fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
