<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_pic_name</name>
   <tag></tag>
   <elementGuidId>b0eaae49-7bfd-4ae7-867f-2c84fdcd257a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pic_name[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pic_name[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4123d07a-c008-498e-98fe-9362b15fd123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70323f1f-4b93-4d53-b9db-8270d9507819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pic_name[]</value>
      <webElementGuid>acf754cc-9840-4041-8635-89cde7e48061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>ffbb63a1-c150-43c0-8e9b-4c0f81d8ec26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pic_field&quot;)/div[@class=&quot;form-group m-b-0 pic-field0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 nopadding&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>df780c8a-9e46-498b-b9c3-b7f17449aaf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pic_name[]']</value>
      <webElementGuid>31a55f32-be8c-4b98-8aa2-fd37b9864a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pic_field']/div/div/div[2]/div/input</value>
      <webElementGuid>9bcac2b6-f2f7-4712-a8b6-c814a855e6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>efff7957-0994-49c2-ae75-a8f471bc83bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pic_name[]']</value>
      <webElementGuid>ccf93012-6670-4898-be04-a2fae7d45cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
