<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_legality_remarks</name>
   <tag></tag>
   <elementGuidId>05b4bc15-fb4f-4681-95c7-64d9fe725636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='legality_remarks[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;legality_remarks[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>213cf340-dc4a-4753-a735-586d2b1d26c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>213930f5-c31e-44a6-a09d-787b4225c36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>legality_remarks[]</value>
      <webElementGuid>54f3020f-dc32-4d8b-85a3-648e2b516441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>6bac4161-ec4b-4ebb-80eb-de958fd5804f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;legalitas_field&quot;)/div[@class=&quot;form-group m-b-0 legalitas-field removeclass0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5 nopadding&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>76af2157-297c-4ab6-8cf8-99d5d3e3c91c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='legality_remarks[]']</value>
      <webElementGuid>4e53c245-4468-47f8-b158-a583768c491e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='legalitas_field']/div/div/div[2]/div/input</value>
      <webElementGuid>6863cdc0-18fe-4ac6-9d0a-99b28dbc536e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>4b2e86fb-7486-45a8-b720-6d54ed0013db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'legality_remarks[]']</value>
      <webElementGuid>e3e846b7-55e2-48cf-ab31-6f985912d11d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
