<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_pic_remarks</name>
   <tag></tag>
   <elementGuidId>f5bad68e-f9f0-4200-8d98-870dbc36bbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pic_remarks[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pic_remarks[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aec82736-1790-4015-8174-d59ae995bde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d9e6e2c-3902-42d9-a25f-de2ad920e53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pic_remarks[]</value>
      <webElementGuid>6dd578ec-f196-41f0-b6e8-9d5854bf5afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>bb2d5271-6d73-4137-93c4-f05b3f3dffc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pic_field&quot;)/div[@class=&quot;form-group m-b-0 pic-field0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 nopadding&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>206042e2-b92a-4d32-a1d1-ff5a5234d517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pic_remarks[]']</value>
      <webElementGuid>dfcec20e-db80-498b-bdab-76c7960f0f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pic_field']/div/div/div[6]/div/input</value>
      <webElementGuid>8c4460be-6886-4e94-bf9d-56816c9020e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>431eb01a-f8cf-4247-bcd8-24c24bb0a644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pic_remarks[]']</value>
      <webElementGuid>8e63688e-6bbb-41d2-955e-e48ff687aefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
