<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_legality_name</name>
   <tag></tag>
   <elementGuidId>fa8f030e-f40d-4dcf-8a29-9274343f5db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='legality_name[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;legality_name[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9c3b241-df96-41a4-b645-1aa17d5184f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bcaf44a-4c6f-41d3-b79b-f23f1eebd9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>legality_name[]</value>
      <webElementGuid>ed3b56de-5f13-45b2-a890-2582c4ad4935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>f2353496-b0f3-4d02-884a-5d6b8b9605d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;legalitas_field&quot;)/div[@class=&quot;form-group m-b-0 legalitas-field removeclass0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 nopadding&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>b9b28886-6607-4eb9-976b-ecaefded7d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='legality_name[]']</value>
      <webElementGuid>c6487aa7-52a5-470a-8065-a8d437e0bc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='legalitas_field']/div/div/div/div/input</value>
      <webElementGuid>1bbc6f94-c526-4154-91fc-330ef5b9754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div/input</value>
      <webElementGuid>7659d576-1cd0-4703-9cb6-8544e91f214c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'legality_name[]']</value>
      <webElementGuid>a690b1b5-be7c-4443-8a88-1cbe841832a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
