<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Transaksi</name>
   <tag></tag>
   <elementGuidId>6fe4c4f2-0881-4d56-b656-31d01697085b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-buying-content > div.modal-footer > #SubmitCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='SubmitCost'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e199192a-efaf-46e6-abca-ab8f56f103b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bb65bf2-4fb2-4375-b87d-c72e7cacbc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitCost</value>
      <webElementGuid>4677d9a6-c841-4899-a031-565ce74df736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn </value>
      <webElementGuid>f131f1f9-e0d1-4aac-8303-0155c08748d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitcost()</value>
      <webElementGuid>8e19eca1-f906-4c9e-9135-493bb099946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>12634fae-2fc6-41af-b20d-6d584a726f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-buying-content&quot;)/div[@class=&quot;modal-footer&quot;]/button[@id=&quot;SubmitCost&quot;]</value>
      <webElementGuid>f5957824-98cf-4c6e-adc0-6e2b32f5feb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='SubmitCost'])[2]</value>
      <webElementGuid>b2f4a349-4e37-4bb1-800f-e069982a43e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-buying-content']/div[3]/button[2]</value>
      <webElementGuid>d3e7c6ca-1a02-4937-aae8-25da0851e0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[12]/following::button[1]</value>
      <webElementGuid>5132fd8c-b74d-40ee-b378-c26b2808fd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number'])[2]/following::button[2]</value>
      <webElementGuid>36381f5c-629f-4359-a1d5-68eb097cad30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[3]/preceding::button[1]</value>
      <webElementGuid>53266c31-a09f-44ab-bacb-eb8b95ef09c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[6]/preceding::button[2]</value>
      <webElementGuid>8fe28684-20b1-4a53-b553-b9aea30d6d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/button[2]</value>
      <webElementGuid>3d0029e0-25c3-4810-b55c-40a6fd8cfd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'SubmitCost' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>c8d9572a-1cff-4123-bec8-1dd432b73341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
