<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__invoice_no</name>
   <tag></tag>
   <elementGuidId>2c1eb6f6-7e0a-45e7-b8a1-e79f7e47cafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invoice_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invoice_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed0e1bb-fbcf-4fc6-a405-be0eb67e8e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>a6420a03-cb3a-48c4-a198-f04f55c0deeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d1c131b-6896-42b5-8433-51e113384a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invoice_no</value>
      <webElementGuid>ab1bcd26-8892-452a-a655-f252d73a3d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invoice_no</value>
      <webElementGuid>b61bf451-e3bd-471f-8971-74f743ca6125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Invoice</value>
      <webElementGuid>efc33cd2-5365-4268-8d45-d5326eef20c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invoice_no&quot;)</value>
      <webElementGuid>a22a57c8-f616-49ac-a25c-aea47cefd4eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invoice_no']</value>
      <webElementGuid>4203385a-6e38-417a-a9db-63eee8f3b99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div/div[3]/input</value>
      <webElementGuid>4942190d-fdaf-4839-bb54-13ec768aab7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c1c070c2-dd9e-4aca-a521-32eceec36da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'invoice_no' and @name = 'invoice_no']</value>
      <webElementGuid>c7ef5400-44bd-4e99-9331-ed27fd5fbe69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
