<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_remarks_cost</name>
   <tag></tag>
   <elementGuidId>dbb42ee9-9acf-4ed9-bcf8-dd3e48d63ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remarks_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remarks_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5955ccad-6053-4314-b5c5-67d5610e53bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dce62a16-12ac-4d47-ab73-5a4230525cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>d96251b4-2f1d-4160-969a-04a3ac3fd633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks_cost</value>
      <webElementGuid>9de1de78-cf71-448f-94ae-bebbdee91770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks_cost</value>
      <webElementGuid>5f709f26-74e9-4517-a389-3e8564491560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks_cost&quot;)</value>
      <webElementGuid>7c250379-4a6b-4479-95b1-d7805c908e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remarks_cost']</value>
      <webElementGuid>6ec94caa-60c2-4cb1-9f5c-bf8e22cfe561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div[5]/input</value>
      <webElementGuid>13ef48dd-675b-41b5-8255-35cf3ddf41ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>0f3fa63b-79ca-4e58-92bb-a6d9ec760c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'remarks_cost' and @name = 'remarks_cost']</value>
      <webElementGuid>e9278b00-a180-4438-8970-15edc0ad0419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
