<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pricecost</name>
   <tag></tag>
   <elementGuidId>9ed422ba-f135-40b2-8d04-1292dc1173a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pricecost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pricecost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d45c548-e5a1-4594-bb09-2586fc257c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fc0c6fe-28ef-46a7-9582-361be944a860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>fd4e4547-0d49-4afe-b2e7-6b5d4281c551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>total_buying();</value>
      <webElementGuid>9ff4bd2c-83b8-4414-8264-e717ffe4d8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pricecost</value>
      <webElementGuid>6b62b611-532f-4c2e-946a-04c7da5df603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pricecost</value>
      <webElementGuid>372c67ff-d225-4124-b42a-7857b5037a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberbuying(event)</value>
      <webElementGuid>d037b038-d232-47f6-80ef-b7344cdf5596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pricecost&quot;)</value>
      <webElementGuid>8d04b4b8-1b7c-4c55-af29-13d9e2c9ba4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pricecost']</value>
      <webElementGuid>74214136-e60d-4d77-adaa-361b44ed0415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div[4]/input</value>
      <webElementGuid>7c1d3ca4-fb59-4b74-8ebf-875b57c9b088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>968ce09e-45c0-4000-b9f4-4d7744b79dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pricecost' and @name = 'pricecost']</value>
      <webElementGuid>b5d1b79c-fd0c-4eb0-a23c-e9fa711fc681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
