<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Alias_item_alias_cost</name>
   <tag></tag>
   <elementGuidId>4adb53b3-c2fa-4d1c-a75e-77d741253fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item_alias_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='item_alias_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65b4ca67-110d-485f-bba7-abd3d458df47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53e02461-e714-4df1-8b63-5937c58b4fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>c6810859-da5a-4beb-9e08-7aa9b033580f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_alias_cost</value>
      <webElementGuid>a0cafecb-4a62-4fdf-9970-d5a552267d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_alias_cost</value>
      <webElementGuid>397f709a-6dc0-44a2-a665-662b8f58a96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_alias_cost&quot;)</value>
      <webElementGuid>7efb79bd-979c-4211-9011-41497a6bcb2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='item_alias_cost']</value>
      <webElementGuid>ef02c08d-cdb6-4fba-83ba-8386ff332011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div[6]/input</value>
      <webElementGuid>4c766d4d-dc87-4df3-b1e8-23f1e47b3d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[6]/input</value>
      <webElementGuid>c9097d4a-8d80-4125-9ef5-0ad80ddaed0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'item_alias_cost' and @name = 'item_alias_cost']</value>
      <webElementGuid>563bb2ca-9ec4-4909-b70e-debc353fac1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
