<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__qty_cost</name>
   <tag></tag>
   <elementGuidId>a12dd9e9-599a-4734-bbd1-cbef9876276d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57bb592e-02ce-448f-80e7-b713f97462fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cd1f48d-c6fe-48d6-8b9e-8dfd66067e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>fa0fc005-c5ba-4f9f-9f5c-480778a132ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>total_buying();</value>
      <webElementGuid>aeb78c32-2197-45a3-b07e-f6d0a0493b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty_cost</value>
      <webElementGuid>e6f9e351-037d-40ad-ae5c-ab0b09a474dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qty_cost</value>
      <webElementGuid>984ab9e7-6215-43c8-bbd5-613f0581ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberbuying(event)</value>
      <webElementGuid>8752481b-ac29-4735-804c-05bbe8a25ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty_cost&quot;)</value>
      <webElementGuid>3a99dd0b-156f-41d4-ac5b-f70de98228b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty_cost']</value>
      <webElementGuid>5e922e93-30ad-4221-a699-2f0ad76b4b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div[3]/input</value>
      <webElementGuid>3514b2f2-f1f4-4f35-9606-90a1f92e404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>caedbc01-9b11-464f-b123-7d32c9aa3eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'qty_cost' and @name = 'qty_cost']</value>
      <webElementGuid>646f06a1-dc5d-4f16-ba94-29d1fd25921a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
