<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buying_number_text_cost</name>
   <tag></tag>
   <elementGuidId>c55bab6f-a218-4a7c-a02a-920f0fe6a7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number_text_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number_text_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c929bab-8980-4651-87fa-f225d2a3e0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f26bee0-d75e-47be-abab-c525a0e327d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>a23e6f47-0cec-461f-a702-96edf009526a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number_text_cost</value>
      <webElementGuid>31e9ad3f-172f-4c57-81fe-efa92591e402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_text_cost</value>
      <webElementGuid>5db94b70-4c18-4b71-984f-a40cb865d9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_text_cost&quot;)</value>
      <webElementGuid>77b487c6-8594-45af-a984-32b214cf7876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number_text_cost']</value>
      <webElementGuid>e5a514f4-4296-4e5c-bb8b-168fbe4c15a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div/div/div/input</value>
      <webElementGuid>47fd4cdb-a9cd-4594-acf7-acb31ece5b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>907a323c-0cc1-4614-96d7-3ff8dd96b5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'number_text_cost' and @id = 'number_text_cost']</value>
      <webElementGuid>de93e723-d063-4778-b094-b49ce73aa6c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
