<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_1_2</name>
   <tag></tag>
   <elementGuidId>bd955af2-103d-418a-975a-abb2f259cd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-type_faktur-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-type_faktur-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1f4d546-dfeb-4e04-9194-23c2676fb32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>58fa03ae-63d6-4cd1-900b-1b56e4c3b719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-type_faktur-container</value>
      <webElementGuid>21620319-324a-46a7-b050-72c7bfc4d7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>9b7f7dba-2096-4e39-90d3-770431f61b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-type_faktur-container&quot;)</value>
      <webElementGuid>6c76a969-03a4-4de9-84e6-7997d4914aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-type_faktur-container']</value>
      <webElementGuid>b233023e-ac48-4e50-a190-afb567140dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div/div[15]/span/span/span/span</value>
      <webElementGuid>ac08f323-494b-4b21-bfc8-a202043c9733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Faktur'])[1]/following::span[4]</value>
      <webElementGuid>5fc5d4b6-edf9-4767-9d92-02e93f3ca397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Invoice(yyyy/mm/dd)'])[1]/following::span[4]</value>
      <webElementGuid>fade9af3-72ac-4874-977a-a18f24877301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payable Account?'])[1]/preceding::span[4]</value>
      <webElementGuid>8b921772-1266-4b03-8420-c86a7a6391ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/span/span/span/span</value>
      <webElementGuid>8837211a-1d9f-4d01-9202-fca8e91153b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-type_faktur-container' and (text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>94a42e00-e798-4023-9c6f-b2b4eecbbfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
