<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_1</name>
   <tag></tag>
   <elementGuidId>7a2e479a-147f-40c5-bea4-5ea2a8a946f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-desc_cost-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-desc_cost-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6047e41-3170-4bd2-a187-90177e3adb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>02f1a17a-6656-4ea2-b2fa-9412f2d1f6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-desc_cost-container</value>
      <webElementGuid>0a1671ca-aa31-4de3-9b18-b2c3787ea143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>343ceadb-0bfb-45b5-bfe2-f5f57a0ea86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-desc_cost-container&quot;)</value>
      <webElementGuid>c820aa81-8a83-4ee6-af9d-3a76fb421868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-desc_cost-container']</value>
      <webElementGuid>c15fd651-14a9-4e08-bdf7-7cabf034bb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div/span/span/span/span</value>
      <webElementGuid>aafeba57-f24c-4a34-a0de-134ffbc04e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::span[4]</value>
      <webElementGuid>7616bb2d-1555-4ea2-92d3-7f6cd6118045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::span[4]</value>
      <webElementGuid>4687dd77-1218-4bca-b06e-14e28063cd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/span/span/span</value>
      <webElementGuid>3a31fda6-64bf-4f80-9195-17a7ac92da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-desc_cost-container' and (text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>ebdc5dac-26a1-45cf-bb95-f40d0a38d52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
