<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose</name>
   <tag></tag>
   <elementGuidId>c47791a3-7140-4658-8f06-f0dad78ec435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-id_ppn_cost-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-id_ppn_cost-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78989028-a125-42f9-a5ed-544fea97b88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>52a27b34-e1af-4233-bdbc-961665b2a132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-id_ppn_cost-container</value>
      <webElementGuid>98f7227e-53d4-43de-ae98-4ff7df34944a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>c7480ada-ffd4-451c-86e6-7647ebf05988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-id_ppn_cost-container&quot;)</value>
      <webElementGuid>b87af004-c635-440f-b788-d47f83968be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-id_ppn_cost-container']</value>
      <webElementGuid>66961a55-8195-4d22-9161-af3ad07e633d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div/div[7]/span/span/span/span</value>
      <webElementGuid>600a63be-e4c3-4fa9-a5dd-b5b2d40b814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::span[4]</value>
      <webElementGuid>f2c6c2a3-da36-480f-b56d-f754adc4558a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span/span/span/span</value>
      <webElementGuid>95a22c9b-9f46-4cbe-9a7d-3db20c0fccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-id_ppn_cost-container' and (text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>b28e0306-f4c6-458b-8aae-5a9868711de4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
