<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_1_2_3</name>
   <tag></tag>
   <elementGuidId>a58932c5-fed3-45c1-8a09-e2a6c006f31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-desc_cost_unit-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-desc_cost_unit-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>959c40dc-4ff3-4fdf-85d2-aec9bb55aef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>24e49fd3-c6b3-43cd-9c9e-d81bed8ac4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-desc_cost_unit-container</value>
      <webElementGuid>4ba5af76-2013-4de9-a3f7-d33e9624d04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose</value>
      <webElementGuid>25ad27a3-dbee-469c-a280-06d473332147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-desc_cost_unit-container&quot;)</value>
      <webElementGuid>7272500e-82d9-44d4-84f4-b53e4b4390e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-desc_cost_unit-container']</value>
      <webElementGuid>b74cc8ba-b4cd-47e2-a913-4c6d3832cbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-buying']/div[3]/div[2]/span/span/span/span</value>
      <webElementGuid>e6508321-3547-41e0-b8e5-c1390ced4994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::span[4]</value>
      <webElementGuid>28529a1b-7233-4094-b96a-798bf738272a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HITAM - 123'])[2]/following::span[6]</value>
      <webElementGuid>5f7cd8f4-0efc-49be-b44d-69b648010913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span/span/span/span</value>
      <webElementGuid>fefa5660-e354-44d0-bfd0-1819501494e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-desc_cost_unit-container' and (text() = 'Choose' or . = 'Choose')]</value>
      <webElementGuid>4ca1a1ca-0e6f-481d-a12b-a0ff686bfa13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
