<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_etd</name>
   <tag></tag>
   <elementGuidId>85ad85a3-3203-49e4-83c5-3ffbff8330f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#etd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='etd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ceb6d09-6d5c-4ce3-b22d-1b3c6f89aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00387505-4e66-42b6-84b2-a76b1014af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>etd</value>
      <webElementGuid>3d56492d-1ef8-47f4-be95-aab49ab35cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>851adcc1-4263-4d42-970d-7e5bada91da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>etd</value>
      <webElementGuid>91979bf3-2efc-4859-8967-7cefe38cbf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etd&quot;)</value>
      <webElementGuid>9c8e1c3e-21b5-4058-a19e-3d1d7cb754e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='etd']</value>
      <webElementGuid>f627c808-ccd2-4422-bc68-f92518239e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[5]/div/div/input</value>
      <webElementGuid>c9ea9cd7-a47e-49c2-aa30-ad31c587cace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[5]/div/div/input</value>
      <webElementGuid>bdcdc9c1-9905-4283-ac11-7f7897b646a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'etd' and @id = 'etd']</value>
      <webElementGuid>a924412a-92d0-4e2b-8bb3-a389f01bb0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
