<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_FCL</name>
   <tag></tag>
   <elementGuidId>823910b2-d0ed-4552-8927-73eb61436f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fcl-view > div.form-body > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fcl-view']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ca5eaa1a-c524-476b-824b-d6c4a4694c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fcl</value>
      <webElementGuid>b8f618e0-032b-4d45-b43a-764fd28975e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FCL</value>
      <webElementGuid>1fa97116-ec8b-40c1-a982-0fcc088fb1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fcl-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>cbc5561a-d428-4de2-bb69-19d1a3c163c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fcl-view']/div/label</value>
      <webElementGuid>f2e9d0de-48a2-48da-94d9-fc5f62da0225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/following::label[1]</value>
      <webElementGuid>2f0f4620-1959-4abb-b527-01265b9853cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::label[1]</value>
      <webElementGuid>27250ab5-b323-4c1a-bc74-f50fe286ac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LCL'])[2]/preceding::label[1]</value>
      <webElementGuid>d629dd0b-2e48-413d-a5d8-c5b9e1937de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakbulk'])[1]/preceding::label[2]</value>
      <webElementGuid>6d1c9210-97f1-4e1d-9416-0c37f73991b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/label</value>
      <webElementGuid>09439535-cb5e-4d85-adc8-06898e184d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'FCL' or . = 'FCL')]</value>
      <webElementGuid>b7d58206-2991-40d7-a332-7e4447529469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
