<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nomination</name>
   <tag></tag>
   <elementGuidId>41b278d2-f6b5-4b20-a7af-a9ac4f20a76f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomination-view > div.form-body > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nomination-view']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>07aa97aa-f53c-4fc8-83fb-f6702666ed03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nomination</value>
      <webElementGuid>a15b19e3-5b63-4190-93c2-17fc0d8f233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomination</value>
      <webElementGuid>d2d6ce54-412b-4e8e-88fa-b571048e8fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomination-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>d33f4e8f-d91c-4ad5-8bc9-5d33b9b3762a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nomination-view']/div/label</value>
      <webElementGuid>9e4a87b0-f001-491e-897e-3e60e4cfc49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlock Selling Tab'])[1]/following::label[1]</value>
      <webElementGuid>9cc715cc-0f65-4f0b-8da1-bfc4bfef1cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Jobfile Name &amp; Description'])[1]/following::label[2]</value>
      <webElementGuid>4a681267-18c0-4095-83aa-907da7b62e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Hand'])[1]/preceding::label[1]</value>
      <webElementGuid>bb908752-3e13-42aa-8786-8e39639d787f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate'])[1]/preceding::label[2]</value>
      <webElementGuid>0558a874-008d-4c33-acfb-a7afd772f6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomination']/parent::*</value>
      <webElementGuid>88a27ee8-886a-4901-9fe4-577aab2ff442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/label</value>
      <webElementGuid>bba711b0-52e7-4b67-9466-479b9e75aca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nomination' or . = 'Nomination')]</value>
      <webElementGuid>6d3a040c-5121-4bc4-a1cd-9b15b75c528b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
