<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>custom job name desc-checkbox-input name</name>
   <tag></tag>
   <elementGuidId>16102e70-2817-4c11-b4ca-4ebda702b726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='custom_name_jobfile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;custom_name_jobfile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ba04dca-d3af-4670-aa46-2df8efdc04a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name Jobfile</value>
      <webElementGuid>65812908-6b38-46df-ac92-e02d0b6b5a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom_name_jobfile</value>
      <webElementGuid>201e6836-298b-44a1-86e5-ae00a75b7793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa33c92a-51bc-4fd1-b8cd-e4414522bbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>0adeeda3-8037-4700-a5ba-1f7ad20822b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-name-view&quot;)/div[@class=&quot;form-body&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>15ebc908-51f4-4671-b52b-69c996a8353b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='custom_name_jobfile']</value>
      <webElementGuid>7b5776cc-0139-4d66-8d09-a2e2ed1dc84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-name-view']/div/input</value>
      <webElementGuid>03fc2f3b-2461-4b07-8bae-4a859d9f0cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>fcc62c75-655a-4512-82e0-d64016fcc2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Name Jobfile' and @name = 'custom_name_jobfile' and @type = 'text']</value>
      <webElementGuid>c8b3da4a-493c-453d-9518-003fc259ead2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
