<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>custom job name desc-checkbox-input desc</name>
   <tag></tag>
   <elementGuidId>88e1b170-fee8-4f77-86cf-573345feb17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='custom_desc_jobfile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;custom_desc_jobfile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca114d32-83c4-4716-9c37-a68b732d865e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>fa1f7f14-a7ed-4689-914f-8c2def794437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom_desc_jobfile</value>
      <webElementGuid>8548576e-5088-4084-af20-b83c303ae63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09fe502c-06d1-4f7f-8c12-fea78e12351a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>a416db7a-6a7d-4a73-b2de-a02c143addea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-desc-view&quot;)/div[@class=&quot;form-body&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>f16f278e-e3c7-4f07-b833-400beee13d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='custom_desc_jobfile']</value>
      <webElementGuid>ddb96e62-f38d-4b04-ad6c-1ffd0afc7846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-desc-view']/div/input</value>
      <webElementGuid>564fa7ae-3d25-4d19-be5c-6b9165942bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>2d6eb6a8-d008-4957-92c4-c5986fcdceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Description' and @name = 'custom_desc_jobfile' and @type = 'text']</value>
      <webElementGuid>6bac8da6-eed3-46bf-afbe-0262c6c8cc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
