<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Unlock Selling Tab</name>
   <tag></tag>
   <elementGuidId>877e005c-4774-42d8-a1c9-b3ce230a1bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div/div/div[10]/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-3 > div.row > div.col-md-12 > div.form-body > label.control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>52e583c2-6f9c-4131-bb44-1e185a695889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label</value>
      <webElementGuid>cac00699-5ed3-4529-a702-754fda85d2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>is_nomination</value>
      <webElementGuid>06ffd81a-ce20-47d3-bced-8be6cec45a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unlock Selling Tab</value>
      <webElementGuid>af67adfb-3da0-48bd-85b7-7a1f4f9fdd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;form-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-body&quot;]/label[@class=&quot;control-label&quot;]</value>
      <webElementGuid>4c4c3555-af75-419e-b2fc-6a54b9e08132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[10]/div/div/div/label</value>
      <webElementGuid>202afc19-ea04-45b9-bd1b-432ebe13bcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Jobfile Name &amp; Description'])[1]/following::label[1]</value>
      <webElementGuid>9202786c-d3b3-4558-9d95-5afc31672971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found'])[1]/following::label[2]</value>
      <webElementGuid>d60cd00b-0fdd-4aea-8986-7d19a206f4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[1]/preceding::label[1]</value>
      <webElementGuid>f69896f9-039a-4489-82dc-9118465b1857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Hand'])[1]/preceding::label[2]</value>
      <webElementGuid>a7cafd72-9baa-4b3b-b2f7-9eb1d96eff41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unlock Selling Tab']/parent::*</value>
      <webElementGuid>580679f4-ff6d-4d74-b479-47d75ae1d2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[10]/div/div/div/label</value>
      <webElementGuid>622122f0-e4c6-4d2d-b5fe-2cef81209759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Unlock Selling Tab' or . = 'Unlock Selling Tab')]</value>
      <webElementGuid>e789532b-4cfa-4b6a-a5ad-f1d38518951f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
