<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Breakbulk</name>
   <tag></tag>
   <elementGuidId>b75eaf70-d90a-4fb7-90ce-6a3692e50aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='breakbulk-view']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#breakbulk-view > div.form-body > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>eede9ac8-ef0b-4d6b-ad99-17fa1ad100b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>breakbulk</value>
      <webElementGuid>3505a92c-ec52-44ac-b35e-9ef5ca69511f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Breakbulk</value>
      <webElementGuid>98ce81f6-8161-4621-be11-59b1a3b9074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breakbulk-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>f450e622-28cd-4acd-b24c-f32fdfa0d065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breakbulk-view']/div/label</value>
      <webElementGuid>50bb3184-d7c2-4670-8dd5-b5d7219aaf78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LCL'])[2]/following::label[1]</value>
      <webElementGuid>c52824eb-a173-40e1-bfdf-855b74201dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCL'])[2]/following::label[2]</value>
      <webElementGuid>08531630-e8d0-41c4-8d39-78e015b3097f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roro'])[1]/preceding::label[1]</value>
      <webElementGuid>70d9a196-d389-451d-b08f-87d09a30b78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Type'])[1]/preceding::label[2]</value>
      <webElementGuid>cb5698c1-04d9-438a-95e7-aaf4952d3e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Breakbulk']/parent::*</value>
      <webElementGuid>61826ab6-b151-48b6-b112-e80b0e712b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div/label</value>
      <webElementGuid>5e090634-2302-459b-b361-6f9efa4e72fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Breakbulk' or . = 'Breakbulk')]</value>
      <webElementGuid>488447ea-f45b-404e-8fc3-fe1eecd09174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
