<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_LCL</name>
   <tag></tag>
   <elementGuidId>39a1b2ca-229d-4ca5-8ff3-f222c273ddf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lcl-view']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lcl-view > div.form-body > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dd9df9c8-538c-4481-8808-190bddaa2089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lcl</value>
      <webElementGuid>1420b915-fe39-4c86-8a5e-28ab8a2d541d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LCL</value>
      <webElementGuid>1c5d2bfb-8310-40a9-9feb-d59283ca6dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lcl-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>9d3a8fb2-61ab-4d81-b2e2-085cd6d0c7c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lcl-view']/div/label</value>
      <webElementGuid>67487e7f-46d3-42c6-a6b8-fe36b89cfefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCL'])[2]/following::label[1]</value>
      <webElementGuid>4fc028d3-6405-4a70-a9f9-d500e98a6a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/following::label[2]</value>
      <webElementGuid>5bf194c5-f48b-44a4-90fd-fad2c410170f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakbulk'])[1]/preceding::label[1]</value>
      <webElementGuid>cae9a0fd-879f-4bc2-b5da-b8be533e9515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roro'])[1]/preceding::label[2]</value>
      <webElementGuid>375e818b-124f-425f-b172-84d25a688808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/label</value>
      <webElementGuid>fbd1e22e-00cd-41b9-a988-2c9695f1eaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'LCL' or . = 'LCL')]</value>
      <webElementGuid>3bb1281a-8a2e-4eda-b07c-d27e59131b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
