<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Corporate</name>
   <tag></tag>
   <elementGuidId>0f22fa90-3842-4581-acdb-2229fd2904be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corporate-view']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#corporate-view > div.form-body > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6a3f764c-541b-4c61-99e0-5c0ea43c1f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>corporate</value>
      <webElementGuid>e723694d-c1f9-4123-8bee-a641476c9cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate</value>
      <webElementGuid>f9d08398-a215-448f-870c-39ab16554a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corporate-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>524e92bd-6347-4b39-83f9-bee9507d830b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corporate-view']/div/label</value>
      <webElementGuid>942c6952-2b07-447a-9c67-6248e105cf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Hand'])[1]/following::label[1]</value>
      <webElementGuid>2b434b05-45a6-48e0-b522-fdee7fecc901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[1]/following::label[2]</value>
      <webElementGuid>96e0a251-33ee-4da4-a372-1802e5d5a225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::label[1]</value>
      <webElementGuid>5a83f23d-57d5-4dc5-a5a0-d2656631d1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate']/parent::*</value>
      <webElementGuid>b9e27d80-7ed4-4d88-a566-e9d88214ec47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/label</value>
      <webElementGuid>5b46ddcb-1ec4-49a7-9ec2-26e71ab61b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Corporate' or . = 'Corporate')]</value>
      <webElementGuid>70f19df5-ef59-4563-bac7-45100338606e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
