<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Roro</name>
   <tag></tag>
   <elementGuidId>d8fe5a53-49c9-4078-a85f-2299feeda192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='roro-view']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roro-view > div.form-body > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7ca94237-9369-44c0-bfbc-2703ca704b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>roro</value>
      <webElementGuid>f72e0892-9f91-48db-b864-60c39fb4b8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Roro</value>
      <webElementGuid>a8b1f1e5-9df0-4b65-9866-4b004c05b293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roro-view&quot;)/div[@class=&quot;form-body&quot;]/label[1]</value>
      <webElementGuid>053a00cc-6dba-4e65-8a78-63351c76a73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roro-view']/div/label</value>
      <webElementGuid>61093a8b-663e-456f-8e97-d784b5a01571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breakbulk'])[1]/following::label[1]</value>
      <webElementGuid>8de9762c-c4d0-4cf9-9f1e-a296b24b29c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LCL'])[2]/following::label[2]</value>
      <webElementGuid>6472fd2d-fe7e-4445-a3cb-42bb2a72388e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Type'])[1]/preceding::label[1]</value>
      <webElementGuid>5dde95b3-b271-40df-acd8-0e45a2d3b974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Jobfile ?'])[1]/preceding::label[2]</value>
      <webElementGuid>bcf4690f-ae3d-44fe-85d6-ad2da530b4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Roro']/parent::*</value>
      <webElementGuid>22b996e3-21a8-4aa8-8b3d-b7e9459c23de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/div/label</value>
      <webElementGuid>34de78d9-0a04-4390-a1cd-1703de0743fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Roro' or . = 'Roro')]</value>
      <webElementGuid>e18a0542-a296-4dd3-a928-ce526f711a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
